server:
  port: 8201

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 0
      port: 6379
      host: ${REDIS_HOST:redis}
      password: ${REDIS_PASSWORD:}

logging:
  config: classpath:logback-spring.xml
  file:
    path: /var/logs
  level:
    root: warn
    com.macro.mall: info
    org.springframework: warn

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

sa-token:
  timeout: 3600
  active-timeout: 1800
  refresh-time: 600
  is-concurrent: false
  is-log: false
  is-print: false
