#!/bin/bash
# Docker镜像构建和启动脚本 - 无需IDE

set -e

echo "====================================="
echo "  MALL-SWARM Docker镜像构建脚本"
echo "====================================="

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 获取脚本所在目录
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR"

# 检查Docker Compose命令
check_docker_compose() {
    if docker compose version &> /dev/null; then
        DOCKER_COMPOSE="docker compose"
    elif command -v docker-compose &> /dev/null; then
        DOCKER_COMPOSE="docker-compose"
    else
        echo -e "${RED}❌ 未找到Docker Compose，请先安装${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker Compose: $DOCKER_COMPOSE${NC}"
}

# 检查Maven
check_maven() {
    if ! command -v mvn &> /dev/null; then
        echo -e "${RED}❌ Maven未安装，请先安装Maven${NC}"
        echo "  Debian安装: sudo apt-get install maven"
        exit 1
    fi
    echo -e "${GREEN}✓ Maven: $(mvn -v | head -1)${NC}"
}

# 构建Docker镜像
build_docker_images() {
    echo ""
    echo -e "${YELLOW}[2/3] 使用Maven构建Docker镜像...${NC}"
    
    cd "$PROJECT_ROOT"
    
    # 构建所有模块（包含Docker镜像）
    echo "编译和构建所有模块..." 
    mvn clean install -DskipTests=true -Ddocker.skip=false
    
    echo -e "${GREEN}✓ Docker镜像构建完成${NC}"
    
    # 验证镜像
    echo ""
    echo "已构建的镜像："
    docker images | grep mall || echo "未找到mall镜像"
}

# prepare environment variables file (optional)
prepare_env_file() {
    # if NO_NACOS is set, write a small .env with overrides
    if [[ "$NO_NACOS" == "true" ]]; then
        cat > "$PROJECT_ROOT/document/docker/.env" <<'EOF'
# generated by docker-build-and-run.sh --no-nacos
SPRING_CLOUD_NACOS_DISCOVERY_ENABLED=false
SPRING_CLOUD_NACOS_CONFIG_ENABLED=false
SPRING_CLOUD_DISCOVERY_ENABLED=false
SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=false
# defaults needed by mall-admin when running without Nacos
MINIO_ENDPOINT=http://localhost:9000
MINIO_BUCKET_NAME=mall
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
# direct urls for feign clients used by mall-auth
MALL_ADMIN_URL=http://mall-admin:8080
MALL_PORTAL_URL=http://mall-portal:8085
EOF
        echo -e "${YELLOW}⚙️  Generated .env disabling Nacos clients and adding service URLs${NC}"
    fi
}

# 启动应用容器
start_app_containers() {
    echo ""
    echo -e "${YELLOW}[3/3] 启动应用容器...${NC}"
    
    cd "$PROJECT_ROOT/document/docker"

    # ensure env file exists if required
    prepare_env_file
    
    echo "启动中间件和应用服务（合并网络）..."
    # 使用 -f 合并两个 compose 文件，这样它们会共享同一个网络，服务名可以互相解析
    # 如果生成了 .env，这个命令会自动读取它
    $DOCKER_COMPOSE -f docker-compose-env.yml -f docker-compose-app.yml up -d
    
    echo -e "${GREEN}✓ 应用容器启动完成${NC}"
    wait_for_service_health
}

# 等待所有服务健康(如果有healthcheck)并打印总结
wait_for_service_health() {
    echo -e "${YELLOW}➤ 等待容器健康状态稳定（超时60s）...${NC}"
    local timeout=60
    local elapsed=0
    while [[ $elapsed -lt $timeout ]]; do
        # grepping for 'unhealthy' or '(health' to detect any non-healthy
        if ! $DOCKER_COMPOSE -f docker-compose-env.yml -f docker-compose-app.yml ps | grep -E "\(unhealthy\|health" >/dev/null; then
            break
        fi
        sleep 2
        elapsed=$((elapsed+2))
    done
    echo -e "${GREEN}✓ 健康检查完成 (等待 ${elapsed}s)${NC}"
    echo "当前容器状态："
    $DOCKER_COMPOSE -f docker-compose-env.yml -f docker-compose-app.yml ps
}

# 显示日志
show_logs() {
    echo ""
    echo "应用启动中，显示日志（按Ctrl+C退出）..."
    sleep 5
    $DOCKER_COMPOSE -f "$PROJECT_ROOT/document/docker/docker-compose-env.yml" -f "$PROJECT_ROOT/document/docker/docker-compose-app.yml" logs -f
}

# parse command line options
NO_NACOS=false
SKIP_BUILD=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --no-nacos)
      NO_NACOS=true
      shift
      ;;
    --skip-build)
      SKIP_BUILD=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# 检查环境
echo -e "${YELLOW}[1/3] 检查构建环境...${NC}"
check_docker_compose
check_maven

if [[ "$SKIP_BUILD" == "false" ]]; then
    # 询问是否构建
    read -p "是否继续构建Docker镜像？(y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "取消构建"
        exit 0
    fi

    # 构建镜像
    build_docker_images
else
    echo -e "${YELLOW}跳过镜像构建 (--skip-build)${NC}"
fi

# 启动容器
start_app_containers

# 显示信息
echo ""
echo "====================================="
echo -e "${GREEN}✓ Docker应用已启动！${NC}"
echo "====================================="
echo ""
echo "访问地址："
echo "  API网关: http://localhost:8201"
echo "  API文档: http://localhost:8201/doc.html"
echo "  Admin后台: http://localhost:8080"
echo "  监控面板: http://localhost:8101"
echo ""
echo "常用命令："
echo "  查看容器: $DOCKER_COMPOSE -f document/docker/docker-compose-app.yml ps"
echo "  查看日志: $DOCKER_COMPOSE -f document/docker/docker-compose-app.yml logs -f"
echo "  停止服务: $DOCKER_COMPOSE -f document/docker/docker-compose-app.yml down"
echo ""
echo "如需跳过 Nacos 客户端，在启动时添加 --no-nacos 参数"
echo "例如： ./docker-build-and-run.sh --no-nacos"
echo ""
echo "按 Ctrl+C 可以停止日志输出"
echo ""

# 显示实时日志
show_logs
